#page title
page_title                                : "Snug: Smart White Noise App"                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                         # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=sleep.baby.white.noise                                          # Enter Google Play Store URL.
presskit_download_link                    :                                            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/snug-logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Snug: Smart White Noise App"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : ⭐ 4.7                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Snug helps you or your baby fall into a deep sleep using soothing and calming sounds. Its unique monitor feature detects when your baby cries and helps them back to sleep.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sonic Baume LTD                                
your_link                                 : https://sonic.bau.me
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Monitor
    description                           : Unique feature that detects crying and automatically plays sound on a timer
    fontawesome_icon_name                 : microphone
    
  - title                                 : Perfectly looped sounds
    description                           : Professionally recorded in the highest quality stereo
    fontawesome_icon_name                 : circle-notch

  - title                                 : Protects your privacy
    description                           : Runs offline, without internet access
    fontawesome_icon_name                 : lock

  - title                                 : Timer
    description                           : Stops playing sound after a set duration
    fontawesome_icon_name                 : hourglass-end

  - title                                 : Fade
    description                           : Slowly fades down the sound over a set period
    fontawesome_icon_name                 : arrow-trend-down

  - title                                 : Night light
    description                           : Can use the screen as a night light, with adjustable colour temperature
    fontawesome_icon_name                 : sun
  
  - title                                 : Runs in background
    description                           : Works when phone is in standby, controllable from the lock screen
    fontawesome_icon_name                 : person-running

  - title                                 : Compatible
    description                           : Works with all phones since 2015 (Android 5.0)
    fontawesome_icon_name                 : mobile-retro

  - title                                 : Offline
    description                           : Works offline. No internet connection required.
    fontawesome_icon_name                 : plane-up


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/nyana-stoica-ikGJw9SYUuM-unsplash-smaller.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#654981"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#654981"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
